show databases;
create database phonebook;
show databases;
use phonebook;
show tables;
create table data (name text(50),phone text(50));
show tables;
describe data;
insert into data values("mark","050-5665636");
select * from data;
describe data;
select phone from data where name="mark";
update data set phone="new phone" where name="mark";
select phone from data where name="mark";
